//
//  ProfileModels.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 22.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
  // MARK: Use cases
    enum ShowUser {
        struct Request {
        }
        struct Response {
            var firstName: String?
            var lastName: String?
            var email: String?
            
        }
        struct ViewModel {
            var firstName: String?
            var lastName: String?
            var email: String?
        }
    }
}
