//
//  ProfilePresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 22.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentSomething(response: Profile.ShowUser.Response)
}

class ProfilePresenter: ProfilePresentationLogic {
    weak var viewController: ProfileDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: Profile.ShowUser.Response) {
        let viewModel = Profile.ShowUser.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
