//
//  ProfilePresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 22.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentUser(response: Profile.ShowUser.Response)
}

class ProfilePresenter: ProfilePresentationLogic {
    weak var viewController: ProfileDisplayLogic?
  
    // MARK: Present User
  
    func presentUser(response: Profile.ShowUser.Response) {
        let viewModel = Profile.ShowUser.ViewModel(firstName: response.firstName?.capitalized,
                                                   lastName: response.lastName?.capitalized,
                                                   email: response.email
        )
        viewController?.displayUser(viewModel: viewModel)
    }
    
    // MARK: Present Logout

}
