//
//  ProfileInteractor.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 22.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func doSomething(request: Profile.ShowUser.Request)
}

protocol ProfileDataStore {
    //var name: String { get set }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: Profile.ShowUser.Request) {
        
    
        let response = Profile.ShowUser.Response()
        presenter?.presentSomething(response: response)
    }
}
