//
//  LoginPresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 11.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentLogin(response: Login.User.Response)
    func presentGoogleLogin()
    func presentFacebookLogin()
    func presentIncorrectPassword()
    func presentEmptyFields()
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?

    // MARK: Present User

    func presentLogin(response: Login.User.Response) {
        let viewModel = Login.User.ViewModel(email: response.email, password: response.password)
        viewController?.displayLogin(viewModel: viewModel)
    }
    
    func presentGoogleLogin() {
        viewController?.displayGoogleLogin()
    }
    
    func presentFacebookLogin() {
        viewController?.displayFacebookLogin()
    }
    
    // MARK: Present Alerts
    
    func presentIncorrectPassword() {
        viewController?.showIncorrectPasswordAlert()
    }
    
    func presentEmptyFields() {
        viewController?.showEmptyFieldsAlert()
    }
}
