//
//  LoginViewController.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 11.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: AnyObject {
    func displayLogin(viewModel: Login.User.ViewModel)
    func showIncorrectPasswordAlert()
}

class LoginViewController: UIViewController, LoginDisplayLogic, UITextFieldDelegate {
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
      
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
  // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        email.delegate = self
        password.delegate = self
    }
  
    // MARK: Login IBOutlets & IBActions
  
    @IBOutlet weak var email: UITextField!
    @IBOutlet weak var password: UITextField!
    
    @IBAction func pressLogin(_ sender: UIButton) {
        if areSomeFieldsEmpty() {
            self.showAlertMessage(message: AlertController.fieldsEmpty.rawValue)
            return
        }
        login()
    }
    
    @IBAction func pressSignUp(_ sender: UIButton) {
        router?.routeToRegistration(segue: nil)
    }
    
    // MARK: Fetch login
    
    func login() {
        let userEmail = email.text
        let userPassword = password.text
        let request = Login.User.Request(email: userEmail, password: userPassword)
        interactor?.login(request: request)
    }
  
    func displayLogin(viewModel: Login.User.ViewModel) {
        if viewModel.success == true {
            router?.routeToTabBar(segue: nil)
            print("Success")
        }
    }
    
    func showIncorrectPasswordAlert() {
        self.showAlertMessage(message: AlertController.incorrectPassword.rawValue)
    }
    
    private func areSomeFieldsEmpty() -> Bool {
       email.text!.isEmpty || password.text!.isEmpty
    }
}
