//
//  LoginInteractor.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 11.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func login(request: Login.User.Request)
}

protocol LoginDataStore {
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    let defaults = UserDefaults.standard
    //var name: String = ""
  
    // MARK: Do something
    
    func login(request: Login.User.Request) {
        let user = CoreDataManager()
        if user.fetchUser(email: request.email, password: request.password) {
            defaults.set(request.email, forKey: UserDefaultsKeys.loggedInUserEmail.rawValue)
            let response = Login.User.Response(email: request.email, password: request.password)
            presenter?.presentLogin(response: response)
        } else {
            presenter?.presentIncorrectPassword()
        }
    }
}
