//
//  ListPresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 14.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentBeers(response: List.ShowBeers.Response)
}

class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?
  
    // MARK: Present Beers
  
    func presentBeers(response: List.ShowBeers.Response) {
        let displayedBeers = convertBeers(beers: response.beers)
        let viewModel = List.ShowBeers.ViewModel(displayedBeers: displayedBeers)
        viewController?.displayBeers(viewModel: viewModel)
    }
    
    private func convertBeers(beers: [BeerItem]) -> [List.ShowBeers.ViewModel.DisplayedBeer] {
        return beers.map { List.ShowBeers.ViewModel.DisplayedBeer(name: $0.name, year: $0.first_brewed, image: $0.image_url) }
    }
}
