//
//  DetailInteractor.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 30.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func provideBeerDetails(request: Detail.ShowDetail.Request)
    func setFavoriteStatus()
}

protocol DetailDataStore {
    var beer: BeerItem! { get set }
    var isFavorite: Bool { get }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    var beer: BeerItem!
    var isFavorite: Bool = false
  
    // MARK: Fetch Beer Details
  
    func provideBeerDetails(request: Detail.ShowDetail.Request) {
        BeerAPI.shared.fetchRandomData(api: "https://api.punkapi.com/v2/beers/\(beer.id)") { [self] beer in
            self.beer = beer
        }
        let response = Detail.ShowDetail.Response(beer: beer, isFavorite: isFavorite)
        presenter?.presentBeerDetails(response: response)
    }
    
    // MARK: Favorite Status
    
    func setFavoriteStatus() {
        isFavorite.toggle()
        let response = Detail.SetFavoriteStatus.Response(isFavorite: isFavorite)
        presenter?.presentFavoriteStatus(response: response)
    }
}
