//
//  DetailModels.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 30.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
  // MARK: Use cases
  
    enum ShowDetail {
        struct Request {
        }
        struct Response {
            let beer: BeerItem?
            let isFavorite: Bool
        }
        struct ViewModel {
            var name: String
            var first_brewed: String
            var image_url: String
            var tagline: String
            var description: String
            let isFavorite: Bool
        }
    }
    
    enum SetFavoriteStatus {
        struct Request {
        }
        struct Response {
            let isFavorite: Bool
        }
        struct ViewModel {
            let isFavorite: Bool
        }
    }
}
