//
//  DetailPresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 30.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentBeerDetails(response: Detail.ShowDetail.Response)
    func presentFavoriteStatus(response: Detail.SetFavoriteStatus.Response)

}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
  
    // MARK: Present Beer Details
  
    func presentBeerDetails(response: Detail.ShowDetail.Response) {
        let viewModel = Detail.ShowDetail.ViewModel(
            name: response.beer!.name,
            first_brewed: response.beer!.first_brewed,
            image_url: response.beer!.image_url,
            tagline: response.beer!.tagline,
            description: response.beer!.description,
            isFavorite: response.isFavorite)
        viewController?.displayBeerDetails(viewModel: viewModel)
    }
    
    // MARK: Present Favorite Status
    
    func presentFavoriteStatus(response: Detail.SetFavoriteStatus.Response) {
        let viewModel = Detail.SetFavoriteStatus.ViewModel(isFavorite: response.isFavorite)
        viewController?.displayFavoriteButtonStatus(viewModel: viewModel)
    }
}
