//
//  InstagramPresenter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 05.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstagramPresentationLogic {
  func presentPhoto(response: Instagram.User.Response)
    func dismissViewController()
}

class InstagramPresenter: InstagramPresentationLogic {
  weak var viewController: InstagramDisplayLogic?
  
  // MARK: Do something
  
  func presentPhoto(response: Instagram.User.Response) {
      let viewModel = Instagram.User.ViewModel(image: response.image)
    viewController?.displayPhoto(viewModel: viewModel)
  }
    
    func dismissViewController() {
        viewController?.dismissViewController()
    }
}
