//
//  RegistrationRouter.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 10.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegistrationRoutingLogic {
    func routeToTabBar(segue: UIStoryboardSegue?)
}

protocol RegistrationDataPassing {
    var dataStore: RegistrationDataStore? { get }
}

class RegistrationRouter: NSObject, RegistrationRoutingLogic, RegistrationDataPassing {
    weak var viewController: RegistrationViewController?
    var dataStore: RegistrationDataStore?
  
    // MARK: Routing
  
//      func routeToTabBar(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//          let destinationVC = segue.destination as! UITabBarController
//          var destinationDS = destinationVC.router!.dataStore!
//          passDataToMain(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: ViewControllers.list.rawValue, bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: ViewControllers.tabBar.rawValue) as! UITabBarController
//          var destinationDS = destinationVC.router!.dataStore!
//          passDataToMain(source: dataStore!, destination: &destinationDS)
//            navigateToTabBar(source: viewController!, destination: destinationVC)
//        }
//
//          let storyboard = UIStoryboard(name: Storyboards.tabBar.rawValue, bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: ViewControllers.tabBar.rawValue) as! UITabBarController
//          navigateToTabBar(source: viewController!, destination: destinationVC)
//      }
    
    func routeToTabBar(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: Storyboards.tabBar.rawValue, bundle: nil)
          let destinationVC = storyboard.instantiateViewController(withIdentifier: ViewControllers.tabBar.rawValue) as! UITabBarController
        navigateToTabBar(source: viewController!, destination: destinationVC)

  }


    // MARK: Navigation
  
    func navigateToTabBar(source: RegistrationViewController, destination: UITabBarController) {
        source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToMain(source: RegistrationDataStore, destination: inout ListDataStore) {

  }
}
