//
//  EditModels.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 26.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Edit {
  // MARK: Use cases
  
    enum User {
        struct Request {
            var firstName: String?
            var lastName: String?
        }
        struct Response {
            var firstName: String
            var lastName: String
        }
        struct ViewModel {
            var firstName: String
            var lastName: String
        }
    }
    
    enum UpdateUser {
        struct Request {
            var firstName: String
            var lastName: String
        }
    }
}
