//
//  RandomViewController.swift
//  Beer_Library
//
//  Created by Vitalina Nazaruk on 22.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation
import Kingfisher
import MapKit
import UIKit

protocol RandomDisplayLogic: AnyObject {
    func displayRandomBeer(viewModel: Random.ShowDetails.ViewModel)
    func displayFavoriteButtonStatus(viewModel: Random.SetFavoriteStatus.ViewModel)
    func displayPin(viewModel: Random.Pin.ViewModel)
    func displayGoogleMapItem(viewModel: Random.MapItem.ViewModel)
    func displayLocation(viewModel: Random.Location.ViewModel)
}

class RandomViewController: UIViewController, RandomDisplayLogic {
    var interactor: RandomBusinessLogic?
    var router: (NSObjectProtocol & RandomRoutingLogic & RandomDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = RandomInteractor()
        let presenter = RandomPresenter()
        let router = RandomRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchRandomBeer()
        determineCurrentLocation()
        fetchLocationPin()
    }
  
    // MARK: Random IBOutlets
  
    @IBOutlet weak var imageBeer: UIImageView!
    @IBOutlet weak var nameBeer: UILabel!
    @IBOutlet weak var yearBeer: UILabel!
    @IBOutlet weak var taglineBeer: UILabel!
    @IBOutlet weak var descriptionBeer: UILabel!
    @IBOutlet weak var mapView: MKMapView!
    @IBOutlet weak var favoriteButton: UIBarButtonItem!
    
    var locationManager = CLLocationManager()

    // MARK: Random Details
    
    func fetchRandomBeer() {
        interactor?.fetchRandomBeer()
    }
    
    @IBAction func tapRandomButton(_ sender: UIButton) {
        fetchRandomBeer()
        fetchLocationPin()
    }
  
    func displayRandomBeer(viewModel: Random.ShowDetails.ViewModel) {
        nameBeer.text = viewModel.name
        yearBeer.text = viewModel.first_brewed
        taglineBeer.text = viewModel.tagline
        descriptionBeer.text = viewModel.description
        imageBeer.kf.setImage(with: URL(string: viewModel.image_url))
        favoriteButton.image = viewModel.image
        navigationItem.title = viewModel.name
    }
    
    // MARK: Favorite Button
    
    @IBAction func toggleFavoriteButton(_ sender: UIBarButtonItem) {
            interactor?.checkButtonState()
    }
    
    func displayFavoriteButtonStatus(viewModel: Random.SetFavoriteStatus.ViewModel) {
         favoriteButton.image = viewModel.isFavorite ? UIImage(systemName: "star.fill") : UIImage(systemName: "star")
    }
    
    // MARK: Direction
    
    func determineCurrentLocation() {
        locationManager.delegate = self
        locationManager.requestWhenInUseAuthorization()
        locationManager.startUpdatingLocation()
    }
    
    func fetchLocationPin() {
        interactor?.fetchLocationPin()
    }
    
    func openGoogleMap() {
        interactor?.fetchGoogleMapItem()
    }
    
    @IBAction func tapGetDirectionButton(_ sender: UIButton) {
        openGoogleMap()
    }
    
    func displayLocation(viewModel: Random.Location.ViewModel) {
        let region = MKCoordinateRegion(center: viewModel.location, span: MKCoordinateSpan(latitudeDelta: 0.02, longitudeDelta: 0.02))
        mapView!.setRegion(region, animated: true)
    }
    
    func displayPin(viewModel: Random.Pin.ViewModel) {
        mapView.addAnnotation(viewModel.pin!)
    }
    
    func displayGoogleMapItem(viewModel: Random.MapItem.ViewModel) {
        let mapItem = viewModel.mapItem
        mapItem!.openInMaps(launchOptions: [MKLaunchOptionsDirectionsModeKey: MKLaunchOptionsDirectionsModeDriving])
    }
}

extension RandomViewController: MKMapViewDelegate, CLLocationManagerDelegate {
    
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        let request = Random.Location.Request(locations: locations)
        interactor?.fetchLocation(request: request)
    }
    
    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
            print("Error - locationManager: \(error.localizedDescription)")
    }
}
